Breaking pre-commit script down into functions

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,4 +1,28 @@
 #!/bin/sh
+handleMergeCommit() {
+  if [ -f .git/MERGE_HEAD ]
+  then
+    echo "[git pre-commit hook] - Merge in progress. Exiting pre-commit hook."
+    exit 0
+  fi
+}
+
+handleEmptyCommitAtStart() {
+  git diff --cached --quiet
+  GIT_DIFF=$?
+  if [ "$GIT_DIFF" -eq 0 ]; then
+    echo "[git pre-commit hook] - No changes to commit! This is likely a rebase or merge commit. Exiting pre-commit hook."
+    exit 0
+  fi
+}
+
+stageUnStagedChangesInStagedFiles() {
+  STAGED_FILES=$(git diff --name-only --cached --diff-filter=ad)
+  if [ -n "$STAGED_FILES" ]; then
+    echo "$STAGED_FILES" | xargs git add
+  fi
+}
+
 spotlessApply() {
   # We pass in ratchetFrom here to ensure that we only format the files that have changed since the last commit
   if command -v mvn >/dev/null 2>&1; then    # Check if mvn command exists to support GitHub Desktop on Windows
@@ -8,80 +32,56 @@ spotlessApply() {
   fi
 }
 
-if [ -f .git/MERGE_HEAD ]
-then
-  echo "[git pre-commit hook] - Merge in progress. Exiting pre-commit hook."
-  exit 0
-fi
+handleMergeConflicts() {
+  conflictedFiles="$(git diff --name-only --diff-filter=U)"
+  if [ -n "$conflictedFiles" ]; then
+    for conflictedFile in $conflictedFiles; do
+      echo "[git pre-commit hook] - Resolving conflict for $conflictedFile"
+      git checkout --theirs "$(pwd)/$conflictedFile"
+      git restore --staged "$(pwd)/$conflictedFile"
 
-git diff --cached --quiet
-GIT_DIFF=$?
-if [ "$GIT_DIFF" -eq 0 ]; then
-  echo "[git pre-commit hook] - No changes to commit! This is likely a rebase or merge commit. Exiting pre-commit hook."
-  exit 0
-fi
+      if command -v mvn >/dev/null 2>&1; then
+        mvn spotless:apply -DspotlessFiles=".*$conflictedFile" -q
+      else
+        ./mvnw spotless:apply -DspotlessFiles=".*$conflictedFile" -q
+      fi
 
-# Add unstaged changes to staged files so that we can prevent conflicts when un-stashing
-STAGED_FILES=$(git diff --name-only --cached --diff-filter=ad)
-if [ -n "$STAGED_FILES" ]; then
-  echo "$STAGED_FILES" | xargs git add
-fi
+      git add "$conflictedFile"
+    done
+  fi
+}
 
-# Stashing unstaged changes - Clear stashes before stashing to prevent conflicts
+handleEmptyCommitAtEnd() {
+  git diff --cached --quiet
+  GIT_DIFF=$?
+  if [ "$GIT_DIFF" -eq 0 ]; then
+    echo "[git pre-commit hook] - No changes to commit! Aborting commit!"
+    # We end up with no changes to commit here due to the stashing and un-stashing of changes
+    # where we stash a bad formatting change, apply the formatting, and then un-stash the bad formatting change.
+    #
+    # Example:
+    #   - We accidentally indented 1 line in a file by an extra space. This causes us to stash the extra space, apply the
+    #     formatting which will remove the extra space, and then un-stash the extra space back into the file that the
+    #     formatter just removed. By re-running spotless:apply, we remove the extra space again and remove the file from
+    #     the staging area.
+    #
+    # This results in no changes to commit, so we exit with 1 to prevent committing an empty commit.
+    # We run spotless:apply again here to ensure that the files are formatted correctly and to remove the file from the staging area.
+    spotlessApply
+    exit 1
+  fi
+}
+
+handleMergeCommit
+handleEmptyCommitAtStart
+stageUnStagedChangesInStagedFiles
 git stash clear
 git stash -q --keep-index
-
 echo "[git pre-commit hook] - Running spotless:apply"
 spotlessApply
 SPOTLESS_APPLY_RESULT=$?
-
-# Staging spotless changes
 git add -u
-
-# Un-stashing changes
 git stash pop -q
-
-# Resolve conflicts if any
-conflictedFiles="$(git diff --name-only --diff-filter=U)"
-if [ -n "$conflictedFiles" ]; then
-  for conflictedFile in $conflictedFiles; do
-    echo "[git pre-commit hook] - Resolving conflict for $conflictedFile"
-    git checkout --theirs "$(pwd)/$conflictedFile"
-    git restore --staged "$(pwd)/$conflictedFile"
-
-    if command -v mvn >/dev/null 2>&1; then
-      mvn spotless:apply -DspotlessFiles=".*$conflictedFile" -q
-    else
-      ./mvnw spotless:apply -DspotlessFiles=".*$conflictedFile" -q
-    fi
-
-    for stagedFile in $STAGED_FILES; do
-      if [ "$stagedFile" = "$conflictedFile" ]; then
-        git add "$conflictedFile"
-        break # Break out of the loop since we found the conflicted file
-      fi
-    done
-  done
-fi
-
-git diff --cached --quiet
-GIT_DIFF=$?
-if [ "$GIT_DIFF" -eq 0 ]; then
-  echo "[git pre-commit hook] - No changes to commit! Aborting commit!"
-  # We end up with no changes to commit here due to the stashing and un-stashing of changes
-  # where we stash a bad formatting change, apply the formatting, and then un-stash the bad formatting change.
-  #
-  # Example:
-  #   - We accidentally indented 1 line in a file by an extra space. This causes us to stash the extra space, apply the
-  #     formatting which will remove the extra space, and then un-stash the extra space back into the file that the
-  #     formatter just removed. By re-running spotless:apply, we remove the extra space again and remove the file from
-  #     the staging area.
-  #
-  # This results in no changes to commit, so we exit with 1 to prevent committing an empty commit.
-  # We run spotless:apply again here to ensure that the files are formatted correctly and to remove the file from the staging area.
-  spotlessApply
-  exit 1
-fi
-
-# Return the 'spotless:apply' exit code
+handleMergeConflicts
+handleEmptyCommitAtEnd
 exit $SPOTLESS_APPLY_RESULT
